name: Build
on: [push, pull_request]
env:
  CI: true
jobs:
  test:
    name: 'Test on Node.js ${{ matrix.node-version }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup staging environment
        run: |
          touch .env.staging
          echo NODE_ENV=${{ secrets.NODE_ENV }} >> .env.staging
          echo HOST=${{ secrets.HOST }} >> .env.staging
          echo PORT=${{ secrets.PORT }} >> .env.staging
          echo ACUITY_BASE_URL=${{ secrets.ACUITY_BASE_URL }} >> .env.staging
          echo ACUITY_USER_ID=${{ secrets.ACUITY_USER_ID }} >> .env.staging
          echo ACUITY_API_KEY=${{ secrets.ACUITY_API_KEY }} >> .env.staging
          cat .env.staging
      - name: Install
        run: npm install
      - name: Prettier
        run: npm run prettier
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Coverage
        uses: codecov/codecov-action@v1
